import { PropertyDescriptor, PropertyRegistry } from './registry.js';
import { PropertyCategory, PersistenceType, IdentityImportance } from './property.js';

const G = PropertyCategory.Global;
const ID = PropertyCategory.Identity;
const SK = PropertyCategory.Skeleton;
const BD = PropertyCategory.Body;
const FC = PropertyCategory.Face;
const SKN = PropertyCategory.Skin;
const EY = PropertyCategory.Eyes;
const HR = PropertyCategory.Hair;
const EX = PropertyCategory.Expression;

/**
 * Default authoritative set of human properties.
 *
 * This is intentionally a representative subset to keep the first release
 * tractable while exercising the full schema pipeline (identity, anatomy,
 * performance, dependencies, GPU layout). Extend descriptors freely â€” the
 * registry derives ids, offsets, defaults and dirty masks automatically.
 */
export const DEFAULT_PROPERTY_DESCRIPTORS: PropertyDescriptor[] = [
  // ---- Global ----
  {
    path: 'global.height',
    type: 'f32',
    units: 'm',
    min: 0.6,
    max: 2.6,
    default: 1.78,
    category: G,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Medium,
    animationCapable: true,
  },
  {
    path: 'global.scale',
    type: 'f32',
    min: 0.5,
    max: 2.0,
    default: 1.0,
    category: G,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.None,
  },

  // ---- Identity ----
  {
    path: 'identity.id',
    type: 'u32',
    default: 1,
    category: ID,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Critical,
  },
  {
    path: 'identity.seed',
    type: 'u32',
    default: 839202,
    category: ID,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Critical,
  },
  {
    path: 'identity.headProportion',
    type: 'f32',
    min: 0.85,
    max: 1.3,
    default: 1.0,
    category: ID,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'identity.skullWidth',
    type: 'f32',
    min: 0.8,
    max: 1.25,
    default: 1.0,
    category: ID,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'identity.faceAsymmetry',
    type: 'f32',
    min: 0.0,
    max: 0.2,
    default: 0.02,
    category: ID,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Medium,
  },

  // ---- Skeleton ----
  {
    path: 'skeleton.neckLength',
    type: 'f32',
    min: 0.7,
    max: 1.35,
    default: 1.0,
    category: SK,
    persistence: PersistenceType.Anatomical,
    identityImportance: IdentityImportance.Medium,
    dependencies: ['global.height'],
    animationCapable: true,
  },
  {
    path: 'skeleton.spineLength',
    type: 'f32',
    min: 0.75,
    max: 1.3,
    default: 1.0,
    category: SK,
    persistence: PersistenceType.Anatomical,
    identityImportance: IdentityImportance.Medium,
    dependencies: ['global.height'],
    animationCapable: true,
  },
  {
    path: 'skeleton.shoulderWidth',
    type: 'f32',
    min: 0.7,
    max: 1.4,
    default: 1.0,
    category: SK,
    persistence: PersistenceType.Anatomical,
    identityImportance: IdentityImportance.Medium,
    dependencies: ['global.height', 'body.muscularity'],
    animationCapable: true,
  },
  {
    path: 'skeleton.armLength',
    type: 'f32',
    min: 0.75,
    max: 1.3,
    default: 1.0,
    category: SK,
    persistence: PersistenceType.Anatomical,
    identityImportance: IdentityImportance.Low,
    dependencies: ['global.height'],
    animationCapable: true,
  },
  {
    path: 'skeleton.legLength',
    type: 'f32',
    min: 0.75,
    max: 1.3,
    default: 1.0,
    category: SK,
    persistence: PersistenceType.Anatomical,
    identityImportance: IdentityImportance.Low,
    dependencies: ['global.height'],
    animationCapable: true,
  },

  // ---- Body ----
  {
    path: 'body.muscularity',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.48,
    category: BD,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Medium,
    dependencies: ['body.bodyFat'],
    animationCapable: true,
  },
  {
    path: 'body.bodyFat',
    type: 'f32',
    min: 0.02,
    max: 0.6,
    default: 0.21,
    category: BD,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Low,
    animationCapable: true,
  },
  {
    path: 'body.chest',
    type: 'f32',
    min: 0.6,
    max: 1.6,
    default: 1.0,
    category: BD,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Low,
    dependencies: ['body.muscularity'],
  },
  {
    path: 'body.waist',
    type: 'f32',
    min: 0.5,
    max: 1.8,
    default: 1.0,
    category: BD,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Low,
    dependencies: ['body.bodyFat'],
  },
  {
    path: 'body.hips',
    type: 'f32',
    min: 0.6,
    max: 1.7,
    default: 1.0,
    category: BD,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Low,
    dependencies: ['body.bodyFat'],
  },

  // ---- Face ----
  {
    path: 'face.jaw.width',
    type: 'f32',
    min: 0.8,
    max: 1.35,
    default: 1.0,
    category: FC,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
    dependencies: ['face.jaw.projection'],
    lodImportance: 5,
  },
  {
    path: 'face.jaw.projection',
    type: 'f32',
    min: 0.8,
    max: 1.3,
    default: 1.0,
    category: FC,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
    lodImportance: 5,
  },
  {
    path: 'face.nose.width',
    type: 'f32',
    min: 0.6,
    max: 1.6,
    default: 1.0,
    category: FC,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Medium,
    lodImportance: 5,
  },
  {
    path: 'face.nose.length',
    type: 'f32',
    min: 0.7,
    max: 1.4,
    default: 1.0,
    category: FC,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Medium,
    lodImportance: 5,
  },
  {
    path: 'face.mouth.width',
    type: 'f32',
    min: 0.7,
    max: 1.5,
    default: 1.0,
    category: FC,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
    lodImportance: 5,
  },
  {
    path: 'face.cheekHeight',
    type: 'f32',
    min: 0.8,
    max: 1.3,
    default: 1.0,
    category: FC,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Medium,
    lodImportance: 4,
  },
  {
    path: 'face.eyeSpacing',
    type: 'f32',
    min: 0.75,
    max: 1.35,
    default: 1.0,
    category: FC,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
    lodImportance: 5,
  },

  // ---- Skin ----
  {
    path: 'skin.pigmentation',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.6,
    category: SKN,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'skin.baseColorR',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.76,
    category: SKN,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'skin.baseColorG',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.62,
    category: SKN,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'skin.baseColorB',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.55,
    category: SKN,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'skin.roughness',
    type: 'f32',
    min: 0.05,
    max: 1.0,
    default: 0.45,
    category: SKN,
    persistence: PersistenceType.Anatomical,
  },
  {
    path: 'skin.specular',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.5,
    category: SKN,
    persistence: PersistenceType.Anatomical,
  },
  {
    path: 'skin.wetness',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: SKN,
    persistence: PersistenceType.Transient,
  },
  {
    path: 'skin.age',
    type: 'f32',
    min: 0.0,
    max: 100.0,
    default: 30.0,
    category: SKN,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.Medium,
    animationCapable: true,
  },

  // ---- Eyes ----
  {
    path: 'eyes.iridColorR',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.25,
    category: EY,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'eyes.iridColorG',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.45,
    category: EY,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'eyes.iridColorB',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.6,
    category: EY,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'eyes.irisScale',
    type: 'f32',
    min: 0.5,
    max: 1.6,
    default: 1.0,
    category: EY,
    persistence: PersistenceType.Identity,
    identityImportance: IdentityImportance.High,
  },
  {
    path: 'eyes.pupilDilation',
    type: 'f32',
    min: 0.3,
    max: 3.0,
    default: 1.0,
    category: EY,
    persistence: PersistenceType.Transient,
  },

  // ---- Hair ----
  {
    path: 'hair.length',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.55,
    category: HR,
    persistence: PersistenceType.Cosmetic,
    identityImportance: IdentityImportance.None,
    animationCapable: true,
  },
  {
    path: 'hair.density',
    type: 'f32',
    min: 0.1,
    max: 1.0,
    default: 0.8,
    category: HR,
    persistence: PersistenceType.Cosmetic,
    identityImportance: IdentityImportance.None,
  },
  {
    path: 'hair.curl',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.2,
    category: HR,
    persistence: PersistenceType.Cosmetic,
    identityImportance: IdentityImportance.None,
  },
  {
    path: 'hair.colorR',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.12,
    category: HR,
    persistence: PersistenceType.Cosmetic,
  },
  {
    path: 'hair.colorG',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.08,
    category: HR,
    persistence: PersistenceType.Cosmetic,
  },
  {
    path: 'hair.colorB',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.06,
    category: HR,
    persistence: PersistenceType.Cosmetic,
  },
  {
    path: 'hair.gray',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: HR,
    persistence: PersistenceType.Cosmetic,
    animationCapable: true,
  },

  // ---- Expression (performance type â€” never identity) ----
  {
    path: 'expression.blinkLeft',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.blinkRight',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.browDownLeft',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.browDownRight',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.browInnerUp',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.eyeSquintLeft',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.eyeSquintRight',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.eyeWideLeft',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.eyeWideRight',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.mouthSmileLeft',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.mouthSmileRight',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.mouthFrownLeft',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.mouthFrownRight',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.jawOpen',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.jawForward',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.mouthPucker',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.tongueOut',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.cheekSquintLeft',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
  {
    path: 'expression.cheekSquintRight',
    type: 'f32',
    min: 0.0,
    max: 1.0,
    default: 0.0,
    category: EX,
    persistence: PersistenceType.Performance,
    animationCapable: true,
  },
];

/** A convenient prebuilt registry with the default descriptors registered. */
export function createDefaultRegistry(): PropertyRegistry {
  const registry = new PropertyRegistry();
  registry.register(DEFAULT_PROPERTY_DESCRIPTORS);
  return registry;
}
